### PR TITLE
feature: Get Subjects for a Course

### PR DESCRIPTION
**Pull request by Ayobamiu**
### What does this PR do?
- Endpoint to get all Subjects for a Course
- Unit tests for getting the Subjects for a Course

### Description of tasks completed
Have the following Endpoints working
`GET /api/v1/subjects/:courseId/subjects

`

### How should this be manually tested?
-  Clone this repository to your local machine
-  Run `npm install` to install node packages
-  Run `npm run dev` to start Server
-  Using Postman,  test the endpoint
-  Run `npm run test` to run unit test

postman

### CODE REVIEW

**Comment by jiokeokwuosa** [comment]
> 
> ### What does this PR do?
> 
>     * Endpoint to get all Courses
> 
>     * Unit tests for getting the courses
> 
> 
> ### Description of tasks completed
> 
> Have the following Endpoints working
> `GET /api/v1/subjects/:courseId/subjects
> 
> `
> ### How should this be manually tested?
> 
>     * Clone this repository to your local machine
> 
>     * Run `npm install` to install node packages
> 
>     * Run `npm run dev` to start Server
> 
>     * Using Postman,  test the endpoint
> 
>     * Run `npm run test` to run unit test
> 
> 
> postman

The description of your PR said "Endpoint to get all courses"

**Comment by jiokeokwuosa** [comment]
your screenshot is not showing subject, am seeing course

**Comment by jiokeokwuosa** [comment]
The endpoint should return the likes of English, Maths linked to a course

**Comment by Ayobamiu** [comment]
The screenshots has been fixed

**Comment by Ayobamiu** [comment]
Because subjects don't have property "name", it can't return English or Mathematics. It will only return mainSubjectId referring to English or Mathematics.

**Comment by jiokeokwuosa** [comment]
> 
> ### What does this PR do?
> 
>     * Endpoint to get all Courses
> 
>     * Unit tests for getting the courses
> 
> 
> ### Description of tasks completed
> 
> Have the following Endpoints working
> `GET /api/v1/subjects/:courseId/subjects
> 
> `
> ### How should this be manually tested?
> 
>     * Clone this repository to your local machine
> 
>     * Run `npm install` to install node packages
> 
>     * Run `npm run dev` to start Server
> 
>     * Using Postman,  test the endpoint
> 
>     * Run `npm run test` to run unit test
> 
> 
> postman

The name of each subject should be linked in the response

**Pull request merged**
